### ISSUE TITLE
Exception in Method list browser

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#106]
GemStone: 3.3.3, Jade 2.1.7
If i save a method in the browser, in most cases i get this exception.

![image](https://user-images.githubusercontent.com/1876280/27951441-3f4736d8-6305-11e7-87f1-8af624c0d72b.png)

**Comment by jgfoster** [comment]
Clearly a problem, but I'm not able to easily reproduce it. Any idea what distinguishes the successes from the failures?

**Comment by obi068** [comment]
Not really, but its not always the same class, and at the moment 
i always get an exception if i use this browser

**Comment by jgfoster** [comment]
Using GS 3.3.3 and Jade 2.1.7 I'm unable to reproduce the problem using extent0.seaside.dbf and editing each of the methods in #'asAnnouncement'. 

It looks like you are running Jade from within Dolphin. Is that correct? If so, could you try again with f1b995f2939646c347bbdf8716517d7d150577a7 since it includes some additional debugging information? Thanks.

**Comment by obi068** [comment]
No i am not using Dolphin, i have only an old version which does not have this issue.
An old Jade version e.g. 2.0.13 doesn't have this issue.

**Comment by obi068** [comment]
Seems to be fixed with 2.1.13
