### ISSUE TITLE
jade gemstone Version mismatch: client build 3020, server is build 33000

### ISSUE THREAD

**Issue by mstram** [jgfoster/Jade.bak#111]
When trying to run jade from https://github.com/jgfoster/Jade/raw/master/runtime/Jade.zip
(the windows .exe  ... on Win7)

against 👍 
https://downloads.gemtalksystems.com/pub/GemStone64/3.3.6/GemStone64Bit3.3.6-x86_64.Linux.zip

... getting the message in the title of this issue

Unable to create a GemStone session, check netldi log file

Netldi 'gs64ldi' on host 'ubuntu-2gb-tor-01' reports the request failed

Will jade work with any of the older versions on the gemtalksystems.com download page ?
(I'll download them and try ;) )

**Comment by jgfoster** [comment]
Yes, the latest Jade should work with 3.3.6 (and with almost any other version you are likely to encounter, from 32-bit 6.1 to 64-bit 3.4—which is not yet released!). But in order to do so, you have to pick the correct version from the drop-down list before you try the first login. I suspect that you have a version other than 3.3.6 selected in the drop-down list. Please try again and if there is a problem let me know what you set the version to before the login attempt.

**Comment by mstram** [comment]
Duh .. I didn't "notice" the drop down ;) 

It looks like the Jade "display" replaces the Topaz   "exec ....... %"  ?    (with no  "%" necessary ?), is that correct ?

You've done a great job with the program,  obviously it's much "prettier" than Topaz :/

Mike

**Comment by jgfoster** [comment]
Hi Mike,

Glad you were able to get further. Yes, Jade is somewhat of a cross between Topaz and GBS. It is intended to make GemStone feel more like a traditional Smalltalk, with a GUI IDE (the things that you would otherwise do with Topaz), but without the features (and complications) of GBS (for VA or VW). So, unless you are running Jade in a Dolphin development image, you can't see the client Smalltalk, only the server Smalltalk.

Jade has much more than simply a workspace to replace Topaz's exec/run/doit command. In addition to a workspace you should look at the System Browser and Debugger. If you want a brief demo, see https://www.youtube.com/watch?v=dnRB5rBbkiI starting at about 3:30.

James
