### ISSUE TITLE
Jade cannot filein a file it created

### ISSUE THREAD

**Issue by nrgiii** [jgfoster/Jade.bak#121]
If I fileout some classes in UserGlobals (via Fileout Dictinoary) and then attempt to file them in, I get a continuous series of modal pop-up error windows telling me Jade cannot yet handle 'env 0'.  This happens with 3.5.

**Comment by jgfoster** [comment]
Using 3.4.1 (gss64_3_4_x_branch-43410), I can file out a dictionary from the System Browser and the file has a Topaz format, including an occasional "set compile_env: 0" (once each time the method category changes?). I'm then able to file it in by opening the file as a Workspace from the Transcript's File menu, then selecting all the text (<Ctrl>+<A>), then selecting 'File In' from the context (right-click) menu. This properly recreated the dictionary.

There may be a difference with the 3.5 Topaz file-out format (Jade's implementation of Topaz is incomplete), so I'll get a 3.5 build and try that out as well.

Also, now that I'm going through the steps it seems that there ought to be a more direct file-in option (opening the file as a workspace, selecting all, then file-in is a bit cumbersome). I'll look at adding a menu to the System Browser's Dictionary menu to do the file-in directly. If the problem was observed from some other path then this will reduce the confusion.

**Comment by jgfoster** [comment]
It turns out that the (unreleased) server version 3.5 has a new Topaz command used by Behavior>>fileOutClass. We support that with 0845c8533aadad0ea9613760dec7508e10ad6612.
