### ISSUE TITLE
Login as HostAgentUser fails with privilege error

### ISSUE THREAD

**Issue by nrgiii** [jgfoster/Jade.bak#130]
Login to 3.5 as HostAgentUser fails due to a privilege error, probably lack of code modification privilege.  It would be nice if Jade could login without this privilege (a warning would be ok) so that code could be inspected but not modified. I suspect this limitation applies to any UserProfile without code modification privilege.

**Comment by jgfoster** [comment]
I suspect you are right. The current design requires a server-based object that we create at each login (allowing us to log in to any stone). For your use case would it be okay to require someone (DataCurator?) to load Jade code somewhere that is visible. Then, without code modification (compile) privileges, could we still do a perform? Could I send #'new' to the JadeServer class to get a helper instance? Then we could verify the correct version of the helper (matching the Jade client). Jade could be modified to have an option to dump the helper install script.

A redesign to work without a server-side helper would be quite significant. GBS does this now but I believe Martin plans to move toward a server-side helper for GBS as well.

**Comment by jgfoster** [comment]
Current idea (design) is to allow you to save the JadeServer (sub)class from another UserProfile. If we get an error that we don't have code modification (compile) privileges, then look for JadeServer and use a new instance of it. We could even consider checking for it first. It would add an additional round-trip to the login but if it were present it would speed things up since we wouldn't need to compile a huge string. 

The primary complication in saving the JadeServer class is that it would be out-of-date with many Jade releases. This would call for a version check.

**Comment by nrgiii** [comment]
This issue has come up again with our Swiss customer.  It would be nice if Jade did the following:
1) If the correct version of JadeServer is present in GemStone, proceed without requiring CodeModification privilege.
2) If not, attempt to compile JadeServer
3) If that fails, raise a coherent error describing if the JadeServer was not found at all or if the wrong version is in the database.

In any case, the desire is to have Jade functional without CodeModification privilege provided the JadeServer class is already in the database.  Perhaps JadeServer should be placed in Globals so that all logins can see it.

**Comment by jgfoster** [comment]
To login without code modification privilege, you will need to first install JadeServer so that it is visible to the user without code modification privilege:

* Using Jade, log in to a stone with the same version (e.g., 3.2.15) where you have code modification privilege (such as a different user on the same stone);
* From the Jade Transcript, select the Jade menu and the 'File out JadeServer' menu command;
* Save the text file to a convenient location;
* Using Topaz, log in to the stone as SystemUser (or edit the file to select another SymbolDictionary, such as Published, and login as another user, e.g., DataCurator);
* Input the file and commit; and
* Using Jade, log in as any user and the pre-installed classes should be used.

The requirement to file out from a logged-in session allows us to use the server code that exports in a Topaz format (this isn't how we internally create JadeServer on login if it isn't present).

If the installed version of JadeServer does not match the client version of Jade (see the 'About Jade' menu) you will be asked whether to use the installed JadeServer. Do so at your own risk!
