### ISSUE TITLE
Backward compatibility JadeDefaultConnection.gss UTF-8 coding

### ISSUE THREAD

**Issue by PeterMoe** [jgfoster/Jade.bak#151]
Hello,
i use Gemstone 2.4.6 and Jade 1.077 because it is very sabil and faster then Jade 2.x.x with my environment.

Now im Testing the newer version Jade 2.1.24-1-g5615471.

When i close Jade 2.1.24-1-g5615471 and want to open Jade 1.077 i get the XML error.

I loaded the file from "C:\Users\<User>\AppData\Roaming\JadeDefaultConnection.gss" 
and read the used coding with Notepad-p-p:

- 1.077 = UTF-8 Without BOM
- 2.1.24 = UTF-8

I converted the saved Jade 2.1.24 JadeDefaultConnection.gss to "UTF-8 without BOM", now i can open Jade 1.077 with the safed 2.1.24 settings.
Jade 2.1.23 used the same coding like Jade 1.077 because there were no problems.
Testing: 
- I started Jade 2.1.24 
- then Jade 2.1.23, didn't load config-file from 2.1.24, no XML Error, using Standard Config.
- then Jade 1.077 no problem loading config from 2.1.23

**Comment by jgfoster** [comment]
I'm wondering if the slow performance is related to #117.
As to opening the settings, this seems again to be UTF-8 related so tied to the new Dolphin 7.1 support. It should be easy to handle the error. I'll work on that soon.

**Comment by jgfoster** [comment]
With 3d65fbb04558e9acfee8898c9167f6c7a5459150 I have changed all file operations to use ANSI rather than UTF-8. This should make any new files backwards compatible with the old versions. Also I've wrapped the process of reading the XML file in an error handler to silently ignore errors and use the default login. I hope to soon replace the existing single XML file with a design that holds several logins (see #119). I'll build and upload a new executable after some other changes.
