### ISSUE TITLE
No error message printed when saving method [Jade 2.4.6/2.4.9, GS 2.4.8]

### ISSUE THREAD

**Issue by macatari** [jgfoster/Jade.bak#279]
When you save a method that has an error in the method editor of the System Browser, you won't get an error message.
The only indication is that the background color doesn't change:

![jade-no-error-message-system-browser](https://user-images.githubusercontent.com/63459547/108889800-1130df00-760d-11eb-85ed-cebba0d4f90f.png)

It works properly in the method editor of the Method List Browser, though:

![jade-no-error-message-implementors-list](https://user-images.githubusercontent.com/63459547/108889853-20b02800-760d-11eb-862c-5d3f79221283.png)

This is with GemStone 2.4.8 and Jade 2.4.9. and was also the case with Jade 2.4.6.

**Comment by jgfoster** [comment]
Instead of inserting text into the method, we now show an error message in the status bar at the bottom of the edit field and we change the highlighting to show a red squiggle line under the error. If you hover over the red squiggle line then you will see the explanation. This allows us to support multiple compile errors and avoids the side-effect of leaving in non-user text in the method. The color should change to have a red tinge when there is an error. The yellow tinge indicates that the text has not been saved.

![Screen Shot 2021-06-14 at 7 26 59 AM](https://user-images.githubusercontent.com/1577872/121908508-eebcf180-cce1-11eb-8098-a12171a6b4fd.png)
