### ISSUE TITLE
Navigation to recently visited methods

### ISSUE THREAD

**Issue by jgfoster** [jgfoster/Jade.bak#39]
Similar to Dolphin's feature

**Comment by brunobuzzi** [comment]
James, i'm working on this (almost finished). The pull request will go next week i think !

**Comment by jgfoster** [comment]
Bruno, thanks for your work on this. Comparing to Dolphin's behavior I find the following:

In Dolphin, on initial open, the buttons are disabled; in Jade, they are enabled (but properly show no methods). Same after the first selection. 

In Dolphin, after the second selection the Back button is enabled and clicking on the drop-down shows one method available. In Jade the Back button drop-down has nothing listed and the Forward button has two things listed, the first method and the current method.

In Jade, selection of class-side methods is not reflected in the history, or if it is included, selection of it is ineffective.

These might be issues I introduced when I reapplied your changes, but I'm not sure.

**Comment by brunobuzzi** [comment]
James,
There is some issues with with this on SystemBrowser (MethodTree explorer works fine).
- I can fix this.
- The are other things because there are lof of bakground processing on System Browser. For example some time the method is missed. This has to do with the category list that at some is erased by SystemBrowser (i do not remember the case exactly).

**Comment by jgfoster** [comment]
On initial method selection, neither forward nor back is enabled (correct).
On second selection, the 'History Forward' button is enabled. This is wrong; the 'History Back' button should be enabled and should return to the first selection.

**Comment by brunobuzzi** [comment]
Ok, this is strange. There is a problem with "queryCommand:". Because if you click on other window and then go back to System Browser --> the enabling/disabling mechanism works fine (backHistory is enabled). I will research on this but it seems a problem with command routing

**Comment by brunobuzzi** [comment]
Fixed the problem you mention. The cause was a forkAt: 3, now changed for fork.
Still there is a couple of bugs when the browser is not able to find the method to select (after selecting a method in of history list). This happend when you select class list then select methods then go to classes hierarchy and selecte method there. When you try to switch between those methods --> the browser is not able to find the method (when i have time i will research on this). But i think the overall functionallity is acceptable.

**Comment by brunobuzzi** [comment]
It seems that removing forkAt: 3 introduced another bug. I have to research this further (methods are associated to wrong classes).  Maybe change fork with a Delay ?

**Comment by jgfoster** [comment]
Comments are invited on pull request #103.

**Comment by jgfoster** [comment]
I think we have a decent implementation of this now. Other problems and refinements can be in separate issues.
