### ISSUE TITLE
Menu Tools - Method changed throw an exception

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#48]
methodsNewerThan: method is not iknown

**Comment by jgfoster** [comment]
It appears that this was introduced by obi068 in August (2db0453).

**Comment by obi068** [comment]
Sorry the misssing methods are part of my commit #42 
Maybe someone could put the methods to the correct GsDevKIT package.

Missing methods:

MethodVersionRecord
_asDateTime
 "use DateTime now if we dont find any useful format"
 | anArray |
 anArray := changeStamp subStrings: $ .
 ^(anArray size == 3 and: [(anArray at: 2) size = 10])
  ifTrue: [DateTime fromString: (anArray at: 2), ' ' ,(anArray at: 3) usingFormat: #(2 1 3 $/ 1 1 $: true false false)]
  ifFalse: [DateTime now]

asCompiledMethod
 | aClass |
 aClass := self behavior.
 ^aClass _fullMethodDictEnv0 at: self selector otherwise: nil

asDateTime
 | aDateTime |
 aDateTime := self dynamicInstVarAt: #dateTime.
 ^aDateTime isNil ifTrue: [self dynamicInstVarAt: #dateTime put: self _asDateTime] ifFalse: [ aDateTime ]

changeStamp: aChangeStamp

 changeStamp := aChangeStamp.
 self asDateTime

MethodVersionHistory
methodsNewerThan: aDateTime
 | result |
 result := Set new.
 self dictionary keysAndValuesDo: [:cl :methodDict | methodDict values do: [:aColl | result addAll: (aColl select: [:methodVersion | methodVersion asDateTime > aDateTime]) ]].
 ^result asSortedCollection: [:a :b | a asDateTime > b asDateTime]

**Comment by jgfoster** [comment]
Jade should not have any dependency on GsDevKit.
